language: node_js
node_js: "12"
branches:
  only:
    - master
cache:
  directories:
    - node_modules
before_install:
  - mysql -e 'CREATE DATABASE job_hunter_db;'
addons:
  apt:
   sources:
    - mysql-5.7-trusty
   packages:
    - mysql-server
    - mysql-client